### ISSUE TITLE
Please document how to run test - on a platform agnostic way

### ISSUE THREAD

**Issue by oz123** [mate-desktop/atril#167]
I will happily make the tests run, but they seem to fail. 
#37 is wrongly closed. Instead the title should be simply updated. 

I just cloned the repository from github, on an up to date gentoo system. 
I also did:

    emerge python-dogtail   

and then 

    wget https://download.gnome.org/sources/pyatspi/2.18/pyatspi-2.18.0.tar.xz

and the rest needed to build `pyatspi-2.18.10` on my system. I can successfully build atril on my machine, and even use it. But the tests fail. 
Here is the log:

```
make check 
....
make  check-TESTS
make[2]: Entering directory '/home/ozn/Software/atril/test'
make[3]: Entering directory '/home/ozn/Software/atril/test'
FAIL: test1.py
FAIL: test2.py
FAIL: test3.py
FAIL: test4.py
FAIL: test5.py
============================================================================
Testsuite summary for atril 1.10.1
============================================================================
# TOTAL: 5
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  5
# XPASS: 0
# ERROR: 0
============================================================================
See test/test-suite.log
Please report to http://www.mate-desktop.org/
============================================================================
Makefile:655: recipe for target 'test-suite.log' failed
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory '/home/ozn/Software/atril/test'
Makefile:761: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/home/ozn/Software/atril/test'
Makefile:862: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/ozn/Software/atril/test'
Makefile:668: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```

And the error log in detail is very similar for the one in #37 
```
 $ cat test/test-suite.log 
=======================================
   atril 1.10.1: test/test-suite.log
=======================================

# TOTAL: 5
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  5
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test1.py
==============

/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py:313: Warning: The property GSettings:schema is deprecated and shouldn't be used anymore. It will be removed in a future version.
  return super_init_func(self, **new_kwargs)
Creating logfile at /tmp/dogtail-ozn/logs/test1_20150928-104750_debug ...
Clicking on [menu | File]
Mouse button 1 click at (403,105)
Warning: ./test1.py:14: The requested widget could not be focused: child with name="Open..." roleName='menu item':
  click('Open...', roleName='menu item')

Traceback (most recent call last):
  File "./test1.py", line 14, in <module>
    click('Open...', roleName='menu item')
  File "/usr/lib64/python2.7/site-packages/dogtail/procedural.py", line 384, in __call__
    Click.node.click(button)
AttributeError: 'NoneType' object has no attribute 'click'

FAIL test1.py (exit status: 1)

FAIL: test2.py
==============

/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py:313: Warning: The property GSettings:schema is deprecated and shouldn't be used anymore. It will be removed in a future version.
  return super_init_func(self, **new_kwargs)
Creating logfile at /tmp/dogtail-ozn/logs/test2_20150928-104752_debug ...
searching for child of [application | atril]: "Enter password" dialog (attempt 3)
searching for child of [application | atril]: "Enter password" dialog (attempt 4)
searching for child of [application | atril]: "Enter password" dialog (attempt 5)
searching for child of [application | atril]: "Enter password" dialog (attempt 6)
searching for child of [application | atril]: "Enter password" dialog (attempt 7)
searching for child of [application | atril]: "Enter password" dialog (attempt 8)
searching for child of [application | atril]: "Enter password" dialog (attempt 9)
searching for child of [application | atril]: "Enter password" dialog (attempt 10)
searching for child of [application | atril]: "Enter password" dialog (attempt 11)
searching for child of [application | atril]: "Enter password" dialog (attempt 12)
searching for child of [application | atril]: "Enter password" dialog (attempt 13)
searching for child of [application | atril]: "Enter password" dialog (attempt 14)
searching for child of [application | atril]: "Enter password" dialog (attempt 15)
searching for child of [application | atril]: "Enter password" dialog (attempt 16)
searching for child of [application | atril]: "Enter password" dialog (attempt 17)
searching for child of [application | atril]: "Enter password" dialog (attempt 18)
searching for child of [application | atril]: "Enter password" dialog (attempt 19)
Warning: ./test2.py:14: The requested widget could not be focused: "Enter password" dialog:
  focus.dialog('Enter password')

Warning: ./test2.py:15: The requested widget could not be focused: child with name="Password Entry" roleName='password text':
  focus.widget('Password Entry', roleName='password text')

Warning: ./test2.py:17: The requested widget could not be focused: child with name="Unlock Document" roleName='push button':
  click('Unlock Document', roleName='push button')

Traceback (most recent call last):
  File "./test2.py", line 17, in <module>
    click('Unlock Document', roleName='push button')
  File "/usr/lib64/python2.7/site-packages/dogtail/procedural.py", line 384, in __call__
    Click.node.click(button)
AttributeError: 'NoneType' object has no attribute 'click'

FAIL test2.py (exit status: 1)

FAIL: test3.py
==============

/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py:313: Warning: The property GSettings:schema is deprecated and shouldn't be used anymore. It will be removed in a future version.
  return super_init_func(self, **new_kwargs)
Creating logfile at /tmp/dogtail-ozn/logs/test3_20150928-104805_debug ...
Clicking on [menu | File]
Mouse button 1 click at (403,105)
Clicking on [menu item | Close]
Traceback (most recent call last):
  File "./test3.py", line 15, in <module>
    click('Close', roleName='menu item')
  File "/usr/lib64/python2.7/site-packages/dogtail/procedural.py", line 384, in __call__
    Click.node.click(button)
  File "/usr/lib64/python2.7/site-packages/dogtail/tree.py", line 473, in click
    rawinput.click(clickX, clickY, button)
  File "/usr/lib64/python2.7/site-packages/dogtail/rawinput.py", line 44, in click
    checkCoordinates(x, y)
  File "/usr/lib64/python2.7/site-packages/dogtail/rawinput.py", line 36, in checkCoordinates
    "Attempting to generate a mouse event at negative coordinates: (%s,%s)" % (x, y))
ValueError: Attempting to generate a mouse event at negative coordinates: (-2147483648,-2147483648)

FAIL test3.py (exit status: 1)

FAIL: test4.py
==============

/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py:313: Warning: The property GSettings:schema is deprecated and shouldn't be used anymore. It will be removed in a future version.
  return super_init_func(self, **new_kwargs)
Creating logfile at /tmp/dogtail-ozn/logs/test4_20150928-104807_debug ...
Clicking on [menu | View]
Mouse button 1 click at (484,105)
Clicking on [menu item | Reload]
Traceback (most recent call last):
  File "./test4.py", line 16, in <module>
    click('Reload', roleName='menu item')
  File "/usr/lib64/python2.7/site-packages/dogtail/procedural.py", line 384, in __call__
    Click.node.click(button)
  File "/usr/lib64/python2.7/site-packages/dogtail/tree.py", line 473, in click
    rawinput.click(clickX, clickY, button)
  File "/usr/lib64/python2.7/site-packages/dogtail/rawinput.py", line 44, in click
    checkCoordinates(x, y)
  File "/usr/lib64/python2.7/site-packages/dogtail/rawinput.py", line 36, in checkCoordinates
    "Attempting to generate a mouse event at negative coordinates: (%s,%s)" % (x, y))
ValueError: Attempting to generate a mouse event at negative coordinates: (-2147483648,-2147483648)

FAIL test4.py (exit status: 1)

FAIL: test5.py
==============

/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py:313: Warning: The property GSettings:schema is deprecated and shouldn't be used anymore. It will be removed in a future version.
  return super_init_func(self, **new_kwargs)
Creating logfile at /tmp/dogtail-ozn/logs/test5_20150928-104808_debug ...
activate on [text | page-label-entry]
Warning: Cannot activate [text | page-label-entry]. It is not sensitive.
Clicking on [menu | File]
Mouse button 1 click at (403,105)
Clicking on [menu item | Close]
Traceback (most recent call last):
  File "./test5.py", line 19, in <module>
    click('Close', roleName='menu item')
  File "/usr/lib64/python2.7/site-packages/dogtail/procedural.py", line 384, in __call__
    Click.node.click(button)
  File "/usr/lib64/python2.7/site-packages/dogtail/tree.py", line 473, in click
    rawinput.click(clickX, clickY, button)
  File "/usr/lib64/python2.7/site-packages/dogtail/rawinput.py", line 44, in click
    checkCoordinates(x, y)
  File "/usr/lib64/python2.7/site-packages/dogtail/rawinput.py", line 36, in checkCoordinates
    "Attempting to generate a mouse event at negative coordinates: (%s,%s)" % (x, y))
ValueError: Attempting to generate a mouse event at negative coordinates: (-2147483648,-2147483648)

FAIL test5.py (exit status: 1)
```

I would really appreciate it if you helped solving this issue.

**Comment by monsta** [comment]
Ok, sorry for misunderstanding. It also turned out that we use ```--disable-tests``` option for distcheck when making tarballs, so ```tests``` dir is skipped, and we never get these errors. I confirm the issue when running ```make check``` manually.

**Comment by oz123** [comment]
Thank you for confirming. Honestly, the tests are quite rudimentry, and I think dogtail itself is quite a dead project. Evince developers, dropped the dogtail test suite, unfortunately.

**Comment by monsta** [comment]
Yes, I've already looked at evince and found out we can't get much help there as they've removed the tests instead of adapting them to the latest changes.

**Comment by oz123** [comment]
The only way to fix those tests, IMHO, is to talk with someone who have some more experience with dogtail. I think atril is also the only project in mate that uses dogtail.

**Comment by NP-Hardass** [comment]
Just an observation, gentoo's dogtail-0.9.0 has dependencies of gtk+3 and libwnck3 whereas the mate packages (on gentoo) are all gtk+2 and libwnck2.  This might explain the test failures in this specific case, though, I can't speak generally as I don't have an atril with gtk+3 instance to check it.

**Comment by monsta** [comment]
We don't have ```dogtail``` package in Debian. For these tests I've used ```python-dogtail``` which simply depends on GI (see the full deps list [here](https://packages.debian.org/jessie/python-dogtail)).

**Comment by oz123** [comment]
I think the problem is that dogtail no longer supports GTK2. 
I tried compiling atril with gtk-3.0, but it fails to start with:

     GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
     Trace/breakpoint trap

**Comment by monsta** [comment]
Oh but you need to build all MATE with GTK+3, or else Atril will be linked with a mix of GTK+2/3 packages which is not allowed (as you can see). :smile:

**Comment by monsta** [comment]
In GTK+3 build all tests are still broken, though with somewhat different error messages. Tested in Debian Testing with python-dogtail 0.9.9. However, the docs that are generated for tests seem ok to me...

**Comment by sc0w** [comment]
`make check` is ok here

all the tests are ok

I did it with `python3-dogtail 0.9.11`

```
PASS: test1.py
PASS: test2.py
PASS: test3.py
PASS: test4.py
PASS: test5.py
============================================================================
Testsuite summary for atril 1.24.0
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```
