### ISSUE TITLE
Segfault with pdf (GTK2)

### ISSUE THREAD

**Issue by gapan** [mate-desktop/atril#239]
Trying to open [this pdf](http://www.cs.princeton.edu/courses/archive/spring17/cos226/exams/de-f16.pdf), atril 1.16.1 segfaults. The segfault only happens with a GTK2 atril. If I compile atril with GTK3, there is no segfault. Also no segfault with evince. All using the same poppler 0.45.0.

Same problem with most of the pdf files from [this page](http://www.cs.princeton.edu/courses/archive/spring17/cos226/exams.html).

Here is what gdb outputs:
```
$ gdb atril
GNU gdb (GDB) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-slackware-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from atril...done.
(gdb) run de-f16.pdf
Starting program: /usr/bin/atril de-f16.pdf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe5e0f700 (LWP 8457)]
[New Thread 0x7fffe560e700 (LWP 8458)]
[New Thread 0x7fffe4e0d700 (LWP 8459)]
[New Thread 0x7fffd71b0700 (LWP 8460)]
[New Thread 0x7fff968ab700 (LWP 8461)]
Vector smash protection is enabled.
[New Thread 0x7fff8cd84700 (LWP 8462)]
[New Thread 0x7fff87fff700 (LWP 8463)]
[New Thread 0x7fff86825700 (LWP 8464)]
[New Thread 0x7fff86024700 (LWP 8465)]
[New Thread 0x7fff85823700 (LWP 8466)]
[New Thread 0x7fff85022700 (LWP 8467)]

Thread 8 "EvJobScheduler" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff87fff700 (LWP 8463)]
0x00007fff8712ff80 in cmsGetColorSpace () from /usr/lib64/../lib64/liblcms2.so.2
(gdb) bt
#0  0x00007fff8712ff80 in cmsGetColorSpace () at /usr/lib64/../lib64/liblcms2.so.2
#1  0x00007fff874a13d9 in GfxICCBasedColorSpace::parse(Array*, OutputDev*, GfxState*, int) () at /usr/lib64/../lib64/libpoppler.so.62
#2  0x00007fff874a0942 in GfxColorSpace::parse(GfxResources*, Object*, OutputDev*, GfxState*, int) () at /usr/lib64/../lib64/libpoppler.so.62
#3  0x00007fff874c5bfa in Page::loadThumb(unsigned char**, int*, int*, int*) () at /usr/lib64/../lib64/libpoppler.so.62
#4  0x00007fff8c140249 in poppler_page_get_thumbnail () at /usr/lib64/../lib64/libpoppler-glib.so.8
#5  0x00007fff8c37f20d in  () at /usr/lib64/atril/3/backends/libpdfdocument.so
#6  0x00007ffff734faf2 in ev_job_thumbnail_run () at /usr/lib64/../lib64/libatrilview.so.3
#7  0x00007ffff7351512 in ev_job_thread_proxy () at /usr/lib64/../lib64/libatrilview.so.3
#8  0x00007fffe9e77275 in  () at /usr/lib64/../lib64/libglib-2.0.so.0
#9  0x00007fffecc47684 in start_thread () at /lib64/libpthread.so.0
#10 0x00007fffe92edefd in clone () at /lib64/libc.so.6
(gdb)
```

**Comment by monsta** [comment]
Familiar backtrace... https://github.com/mate-desktop/atril/issues/222, https://github.com/mate-desktop/atril/issues/234...

**Comment by gapan** [comment]
If the problem is with poppler, then why does it work with atril GTK3 and evince?

**Comment by monsta** [comment]
You can see in the discussion in https://github.com/mate-desktop/atril/issues/222 that it doesn't always happen. But I suggest patching poppler anyway.
