### ISSUE TITLE
test cases fail on debian wheezy

### ISSUE THREAD

**Issue by oz123** [mate-desktop/atril#37]
Here is the output:

```
[31] :~/mate-build/mate-document-viewer  [private]  $ make check
Making check in cut-n-paste
make[1]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/cut-n-paste'
Making check in zoom-control
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/cut-n-paste/zoom-control'
make[2]: Nothing to be done for `check'.
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/cut-n-paste/zoom-control'
Making check in toolbar-editor
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/cut-n-paste/toolbar-editor'
make  check-am
make[3]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/cut-n-paste/toolbar-editor'
make[3]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/cut-n-paste/toolbar-editor'
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/cut-n-paste/toolbar-editor'
Making check in totem-screensaver
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/cut-n-paste/totem-screensaver'
make[2]: Nothing to be done for `check'.
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/cut-n-paste/totem-screensaver'
Making check in smclient
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/cut-n-paste/smclient'
make[2]: Nothing to be done for `check'.
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/cut-n-paste/smclient'
Making check in gimpcellrenderertoggle
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/cut-n-paste/gimpcellrenderertoggle'
make[2]: Nothing to be done for `check'.
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/cut-n-paste/gimpcellrenderertoggle'
Making check in synctex
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/cut-n-paste/synctex'
make[2]: Nothing to be done for `check'.
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/cut-n-paste/synctex'
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/cut-n-paste'
make[2]: Nothing to be done for `check-am'.
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/cut-n-paste'
make[1]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/cut-n-paste'
Making check in data
make[1]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data'
Making check in icons
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons'
Making check in 16x16
make[3]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/16x16'
Making check in actions
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/16x16/actions'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/16x16/actions'
Making check in apps
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/16x16/apps'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/16x16/apps'
Making check in mimetypes
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/16x16/mimetypes'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/16x16/mimetypes'
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/16x16'
make[4]: Nothing to be done for `check-am'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/16x16'
make[3]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/16x16'
Making check in 22x22
make[3]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/22x22'
Making check in actions
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/22x22/actions'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/22x22/actions'
Making check in apps
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/22x22/apps'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/22x22/apps'
Making check in mimetypes
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/22x22/mimetypes'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/22x22/mimetypes'
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/22x22'
make[4]: Nothing to be done for `check-am'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/22x22'
make[3]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/22x22'
Making check in 24x24
make[3]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/24x24'
Making check in actions
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/24x24/actions'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/24x24/actions'
Making check in apps
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/24x24/apps'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/24x24/apps'
Making check in mimetypes
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/24x24/mimetypes'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/24x24/mimetypes'
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/24x24'
make[4]: Nothing to be done for `check-am'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/24x24'
make[3]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/24x24'
Making check in 32x32
make[3]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/32x32'
Making check in actions
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/32x32/actions'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/32x32/actions'
Making check in mimetypes
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/32x32/mimetypes'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/32x32/mimetypes'
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/32x32'
make[4]: Nothing to be done for `check-am'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/32x32'
make[3]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/32x32'
Making check in 48x48
make[3]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/48x48'
Making check in actions
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/48x48/actions'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/48x48/actions'
Making check in apps
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/48x48/apps'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/48x48/apps'
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/48x48'
make[4]: Nothing to be done for `check-am'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/48x48'
make[3]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/48x48'
Making check in scalable
make[3]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/scalable'
Making check in actions
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/scalable/actions'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/scalable/actions'
Making check in apps
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/scalable/apps'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/scalable/apps'
Making check in mimetypes
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/scalable/mimetypes'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/scalable/mimetypes'
make[4]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/scalable'
make[4]: Nothing to be done for `check-am'.
make[4]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/scalable'
make[3]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons/scalable'
make[3]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons'
make[3]: Nothing to be done for `check-am'.
make[3]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons'
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data/icons'
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/data'
make[2]: Nothing to be done for `check-am'.
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data'
make[1]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/data'
Making check in libdocument
make[1]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/libdocument'
make  check-am
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/libdocument'
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/libdocument'
make[1]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/libdocument'
Making check in backend
make[1]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/backend'
Making check in pdf
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/backend/pdf'
make[2]: Nothing to be done for `check'.
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/backend/pdf'
Making check in ps
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/backend/ps'
make[2]: Nothing to be done for `check'.
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/backend/ps'
Making check in djvu
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/backend/djvu'
make[2]: Nothing to be done for `check'.
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/backend/djvu'
Making check in tiff
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/backend/tiff'
make[2]: Nothing to be done for `check'.
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/backend/tiff'
Making check in dvi
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/backend/dvi'
Making check in mdvi-lib
make[3]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/backend/dvi/mdvi-lib'
make[3]: Nothing to be done for `check'.
make[3]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/backend/dvi/mdvi-lib'
make[3]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/backend/dvi'
make[3]: Nothing to be done for `check-am'.
make[3]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/backend/dvi'
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/backend/dvi'
Making check in comics
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/backend/comics'
make[2]: Nothing to be done for `check'.
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/backend/comics'
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/backend'
make[2]: Nothing to be done for `check-am'.
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/backend'
make[1]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/backend'
Making check in libview
make[1]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/libview'
make  check-am
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/libview'
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/libview'
make[1]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/libview'
Making check in libmisc
make[1]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/libmisc'
make[1]: Nothing to be done for `check'.
make[1]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/libmisc'
Making check in properties
make[1]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/properties'
make[1]: Nothing to be done for `check'.
make[1]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/properties'
Making check in shell
make[1]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/shell'
make  check-am
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/shell'
make[2]: Nothing to be done for `check-am'.
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/shell'
make[1]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/shell'
Making check in po
make[1]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/po'
rm -f missing notexist
srcdir=. /usr/bin/intltool-update -m
if [ -r missing -o -r notexist ]; then \
	  exit 1; \
	fi
make[1]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/po'
Making check in help
make[1]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/help'
Making check in reference
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/help/reference'
Making check in libdocument
make[3]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/help/reference/libdocument'
make[3]: Nothing to be done for `check'.
make[3]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/help/reference/libdocument'
Making check in libview
make[3]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/help/reference/libview'
make[3]: Nothing to be done for `check'.
make[3]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/help/reference/libview'
Making check in shell
make[3]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/help/reference/shell'
make[3]: Nothing to be done for `check'.
make[3]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/help/reference/shell'
make[3]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/help/reference'
make[3]: Nothing to be done for `check-am'.
make[3]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/help/reference'
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/help/reference'
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/help'
make[2]: Nothing to be done for `check-am'.
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/help'
for lc in C bg ca cs de el en_GB es eu fi fr it ja nl oc pt_BR ru sl sr sv uk vi zh_CN; do \
	  if test -d "$lc"; \
	    then d=; \
	    xmlpath="$lc"; \
	  else \
	    d="./"; \
	    xmlpath="$lc:./$lc"; \
	  fi; \
	  for page in index.docbook legal.xml; do \
	    echo "xmllint --noout --noent --path $xmlpath --xinclude $d$lc/$page"; \
	    xmllint --noout --noent --path "$xmlpath" --xinclude "$d$lc/$page"; \
	  done; \
	done
xmllint --noout --noent --path C --xinclude C/index.docbook
xmllint --noout --noent --path C --xinclude C/legal.xml
xmllint --noout --noent --path bg --xinclude bg/index.docbook
xmllint --noout --noent --path bg --xinclude bg/legal.xml
xmllint --noout --noent --path ca --xinclude ca/index.docbook
xmllint --noout --noent --path ca --xinclude ca/legal.xml
xmllint --noout --noent --path cs --xinclude cs/index.docbook
xmllint --noout --noent --path cs --xinclude cs/legal.xml
xmllint --noout --noent --path de --xinclude de/index.docbook
xmllint --noout --noent --path de --xinclude de/legal.xml
xmllint --noout --noent --path el --xinclude el/index.docbook
xmllint --noout --noent --path el --xinclude el/legal.xml
xmllint --noout --noent --path en_GB --xinclude en_GB/index.docbook
xmllint --noout --noent --path en_GB --xinclude en_GB/legal.xml
xmllint --noout --noent --path es --xinclude es/index.docbook
xmllint --noout --noent --path es --xinclude es/legal.xml
xmllint --noout --noent --path eu --xinclude eu/index.docbook
xmllint --noout --noent --path eu --xinclude eu/legal.xml
xmllint --noout --noent --path fi --xinclude fi/index.docbook
xmllint --noout --noent --path fi --xinclude fi/legal.xml
xmllint --noout --noent --path fr --xinclude fr/index.docbook
xmllint --noout --noent --path fr --xinclude fr/legal.xml
xmllint --noout --noent --path it --xinclude it/index.docbook
xmllint --noout --noent --path it --xinclude it/legal.xml
xmllint --noout --noent --path ja --xinclude ja/index.docbook
xmllint --noout --noent --path ja --xinclude ja/legal.xml
xmllint --noout --noent --path nl --xinclude nl/index.docbook
xmllint --noout --noent --path nl --xinclude nl/legal.xml
xmllint --noout --noent --path oc --xinclude oc/index.docbook
xmllint --noout --noent --path oc --xinclude oc/legal.xml
xmllint --noout --noent --path pt_BR --xinclude pt_BR/index.docbook
xmllint --noout --noent --path pt_BR --xinclude pt_BR/legal.xml
xmllint --noout --noent --path ru --xinclude ru/index.docbook
xmllint --noout --noent --path ru --xinclude ru/legal.xml
xmllint --noout --noent --path sl --xinclude sl/index.docbook
xmllint --noout --noent --path sl --xinclude sl/legal.xml
xmllint --noout --noent --path sr --xinclude sr/index.docbook
xmllint --noout --noent --path sr --xinclude sr/legal.xml
xmllint --noout --noent --path sv --xinclude sv/index.docbook
xmllint --noout --noent --path sv --xinclude sv/legal.xml
xmllint --noout --noent --path uk --xinclude uk/index.docbook
xmllint --noout --noent --path uk --xinclude uk/legal.xml
xmllint --noout --noent --path vi --xinclude vi/index.docbook
xmllint --noout --noent --path vi --xinclude vi/legal.xml
xmllint --noout --noent --path zh_CN --xinclude zh_CN/index.docbook
xmllint --noout --noent --path zh_CN --xinclude zh_CN/legal.xml
make[1]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/help'
Making check in test
make[1]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/test'
make  test1.py test2.py test3.py test4.py test5.py
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/test'
make[2]: Nothing to be done for `test1.py'.
make[2]: Nothing to be done for `test2.py'.
make[2]: Nothing to be done for `test3.py'.
make[2]: Nothing to be done for `test4.py'.
make[2]: Nothing to be done for `test5.py'.
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/test'
make  check-TESTS
make[2]: Entering directory `/home/ozdeb/mate-build/mate-document-viewer/test'
Creating logfile at /tmp/dogtail-ozdeb/logs/test1_20130927-011918_debug ...
Mouse button 1 click at (22,80)
Warning: ./test1.py:14: The requested widget could not be focused: child with name="Open..." roleName='menu item':
  click('Open...', roleName='menu item')

Traceback (most recent call last):
  File "./test1.py", line 14, in <module>
    click('Open...', roleName='menu item')
  File "/usr/lib/python2.7/dist-packages/dogtail/procedural.py", line 327, in __call__
    Click.node.click(button)
AttributeError: 'NoneType' object has no attribute 'click'

FAIL: test1.py
Command Line Error: Incorrect password
Creating logfile at /tmp/dogtail-ozdeb/logs/test2_20130927-011920_debug ...
searching for child of [application | atril]: "Enter password" dialog (attempt 3)
searching for child of [application | atril]: "Enter password" dialog (attempt 4)
searching for child of [application | atril]: "Enter password" dialog (attempt 5)
searching for child of [application | atril]: "Enter password" dialog (attempt 6)
searching for child of [application | atril]: "Enter password" dialog (attempt 7)
searching for child of [application | atril]: "Enter password" dialog (attempt 8)
Command Line Error: Incorrect password
searching for child of [application | atril]: "Enter password" dialog (attempt 9)
searching for child of [application | atril]: "Enter password" dialog (attempt 10)
searching for child of [application | atril]: "Enter password" dialog (attempt 11)
searching for child of [application | atril]: "Enter password" dialog (attempt 12)
searching for child of [application | atril]: "Enter password" dialog (attempt 13)
searching for child of [application | atril]: "Enter password" dialog (attempt 14)
Command Line Error: Incorrect password
searching for child of [application | atril]: "Enter password" dialog (attempt 15)
searching for child of [application | atril]: "Enter password" dialog (attempt 16)
searching for child of [application | atril]: "Enter password" dialog (attempt 17)
searching for child of [application | atril]: "Enter password" dialog (attempt 18)
searching for child of [application | atril]: "Enter password" dialog (attempt 19)
Warning: ./test2.py:14: The requested widget could not be focused: "Enter password" dialog:
  focus.dialog('Enter password')

Warning: ./test2.py:15: The requested widget could not be focused: child with name="Password Entry" roleName='password text':
  focus.widget('Password Entry', roleName='password text')


(atril:25453): Gtk-CRITICAL **: IA__gtk_widget_event: assertion `WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(atril:25453): Gtk-CRITICAL **: IA__gtk_widget_event: assertion `WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(atril:25453): Gtk-CRITICAL **: IA__gtk_widget_event: assertion `WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(atril:25453): Gtk-CRITICAL **: IA__gtk_widget_event: assertion `WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(atril:25453): Gtk-CRITICAL **: IA__gtk_widget_event: assertion `WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(atril:25453): Gtk-CRITICAL **: IA__gtk_widget_event: assertion `WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(atril:25453): Gtk-CRITICAL **: IA__gtk_widget_event: assertion `WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Warning: ./test2.py:17: The requested widget could not be focused: child with name="Unlock Document" roleName='push button':
  click('Unlock Document', roleName='push button')

Traceback (most recent call last):
  File "./test2.py", line 17, in <module>
    click('Unlock Document', roleName='push button')
  File "/usr/lib/python2.7/dist-packages/dogtail/procedural.py", line 327, in __call__
    Click.node.click(button)
AttributeError: 'NoneType' object has no attribute 'click'

FAIL: test2.py
Creating logfile at /tmp/dogtail-ozdeb/logs/test3_20130927-011932_debug ...
Mouse button 1 click at (22,80)
Mouse button 1 click at (197,340)
PASS: test3.py
Creating logfile at /tmp/dogtail-ozdeb/logs/test4_20130927-011935_debug ...
Mouse button 1 click at (98,80)
Mouse button 1 click at (-2147483648,-2147483648)
Mouse button 1 click at (98,80)
Mouse button 1 click at (-2147483648,-2147483648)
Mouse button 1 click at (98,80)
Mouse button 1 click at (-2147483648,-2147483648)
Mouse button 1 click at (98,80)
Mouse button 1 click at (-2147483648,-2147483648)
Mouse button 1 click at (98,80)
Mouse button 1 click at (-2147483648,-2147483648)
Mouse button 1 click at (22,80)
Mouse button 1 click at (197,340)
PASS: test4.py
Creating logfile at /tmp/dogtail-ozdeb/logs/test5_20130927-011948_debug ...
activate on [text | page-label-entry]
Warning: Cannot activate [text | page-label-entry]. It is not sensitive.

(atril:25437): AtrilDocument-CRITICAL **: ev_document_get_n_pages: assertion `EV_IS_DOCUMENT (document)' failed

(atril:25437): AtrilDocument-CRITICAL **: ev_document_get_n_pages: assertion `EV_IS_DOCUMENT (document)' failed

(atril:25437): AtrilDocument-CRITICAL **: ev_document_has_text_page_labels: assertion `EV_IS_DOCUMENT (document)' failed
Mouse button 1 click at (22,80)
Mouse button 1 click at (197,340)
FAIL: test5.py
=============================================
3 of 5 tests failed
Please report to http://www.mate-desktop.org/
=============================================
make[2]: *** [check-TESTS] Error 1
make[2]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/test'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/home/ozdeb/mate-build/mate-document-viewer/test'
make: *** [check-recursive] Error 1
```

**Comment by monsta** [comment]
Wheezy isn't supported as of MATE 1.10, and there won't be any new 1.8.x upstream releases. If you need some fix for 1.8 in Wheezy, please ask Debian maintainers.

**Comment by oz123** [comment]
@monsta I am sorry to you this, but your bug closing policy is disappointing. I opened this bug in 2013, when wheezy was relevant. I am not using Debian any more, but do test cases work now ?

**Comment by monsta** [comment]
They're invoked during tarball preparation, so apparently they work.

**Comment by oz123** [comment]
So this has nothing to do with the old operating system, Debian Wheezy. This has to do with the tests now fixed on an unknown operating system (you didn't specify which one).
